version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: prime-apache-app
    container_name: prime-apache-container
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: prime-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Ayush3602@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
